env:
  browser: true
  es2021: true
settings:
  react:
    version: detect
extends:
  - plugin:react/recommended
  - standard-with-typescript
  - prettier
overrides:
  - files:
      - '*.stories.@(ts|tsx|js)'
    extends:
      - plugin:storybook/recommended
    rules:
      '@typescript-eslint/consistent-type-assertions': off
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: ./tsconfig.json
plugins:
  - react
rules:
  react/react-in-jsx-scope: off
  '@typescript-eslint/triple-slash-reference': off
  semi:
    - error
    - never
  'no-unexpected-multiline': 'error'
