env:
  browser: true
  es2021: true
settings:
  react:
    version: detect
extends:
  - plugin:react/recommended
  - standard-with-typescript
  - prettier
overrides:
  - files:
      - '*.stories.@(ts|tsx|js)'
    extends:
      - plugin:storybook/recommended
    rules:
      '@typescript-eslint/consistent-type-assertions': off
  - files:
      - '**/__tests__/**/*.+(ts|tsx|js)'
      - '**/?(*.)+(spec|test).+(ts|tsx|js)'
    extends:
      - plugin:jest-dom/recommended
      - plugin:testing-library/react
    rules:
      '@typescript-eslint/no-unused-expressions': off
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project: ./tsconfig.json
plugins:
  - react
  - jest-dom
  - testing-library
rules:
  react/react-in-jsx-scope: off
  '@typescript-eslint/triple-slash-reference': off
  semi:
    - error
    - never
  'no-unexpected-multiline': 'error'
ignorePatterns:
  - vite.config.ts
  - vitest.setup.ts
