version: '3.9'
services:
  react:
    build:
      args:
        - NODE_VER=18.16.0-slim
        - FIREBASE_VER=12.3.0
      context: ./frontend
    tty: true
    environment:
      - VITE_MYWEBSITE_URL=${MYWEBSITE_URL}
      - VITE_MYWEBSITE_NAME=${MYWEBSITE_NAME}
      - VITE_API_KEY=${API_KEY}
      - VITE_AUTH_DOMAIN=${AUTH_DOMAIN}
      - VITE_PROJECT_ID=${PROJECT_ID}
      - VITE_STORAGE_BUCKET=${STORAGE_BUCKET}
      - VITE_MESSAGING_SENDER_ID=${MESSAGING_SENDER_ID}
      - VITE_APP_ID=${APP_ID}
      - FIREBASE_AUTH_EMULATOR_HOST="emulator:9099"
    volumes:
      - ./frontend:/home/node/app
      - node_modules:/home/node/app/node_modules
    ports:
      - 5173:5173
      - 6006:6006

  emulator:
    build:
      args:
        - OPEN_JDK_VER=20-slim
        - NODE_VER=18.16.0-slim
        - FIREBASE_VER=12.3.0
      context: ./firebase_emulator
    tty: true
    environment:
      USE_LOCAL_BACKEND: 1
    working_dir: /opt/workspace
    ports:
      - 4000:4000
      - 9099:9099

volumes:
  node_modules:
