version: '3.9'
services:
  react:
    build:
      args:
        - NODE_VER=16.17.1-slim
      context: .
      dockerfile: Dockerfile
    tty: true
    env_file:
      - .env
    volumes:
      - ./frontend:/home/node/app
      - node_modules:/home/node/app/node_modules
    ports:
      - 5173:5173
      - 6006:6006

volumes:
  node_modules: