version: '3.9'
services:
  react:
    build:
      args:
        - NODE_VER=16.17.1-slim
        - FIREBASE_VER=11.15.0
      context: .
      dockerfile: Dockerfile
    tty: true
    environment:
      - VITE_MYWEBSITE_URL=${MYWEBSITE_URL}
      - VITE_MYWEBSITE_NAME=${MYWEBSITE_NAME}
      - VITE_API_KEY=${API_KEY}
      - VITE_AUTH_DOMAIN=${AUTH_DOMAIN}
      - VITE_PROJECT_ID=${PROJECT_ID}
      - VITE_STORAGE_BUCKET=${STORAGE_BUCKET}
      - VITE_MESSAGING_SENDER_ID=${MESSAGING_SENDER_ID}
      - VITE_APP_ID=${APP_ID}
    volumes:
      - ./frontend:/home/node/app
      - node_modules:/home/node/app/node_modules
    ports:
      - 5173:5173
      - 6006:6006

volumes:
  node_modules: