name: Deploy to Firebase Hosting on merge
'on':
 push:
   branches:
     - main
jobs:
  build_and_deploy:
    name: Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      MYWEBSITE_URL="${{ secrets.MYWEBSITE_URL }}"
      MYWEBSITE_NAME="${{ secrets.MYWEBSITE_NAME }}"
      API_KEY="${{ secrets.FIREBASE_API_KEY }}"
      AUTH_DOMAIN="${{ secrets.FIREBASE_AUTH_DOMAIN }}"
      PROJECT_ID="${{ secrets.FIREBASE_PROJECT_ID }}"
      STORAGE_BUCKET="${{ secrets.FIREBASE_STORAGE_BUCKET }}"
      MESSAGING_SENDER_ID="${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}"
      APP_ID="${{ secrets.FIREBASE_APP_ID }}"
    steps:
      - name: checkout pushed commit
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Build
        run: docker-compose run --rm react yarn build
      - name: Deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_TOKEN }}'
          channelId: live
          projectId: '${{ secrets.FIREBASE_PROJECTID }}'
