name: FrontEnd Testing
on:
  pull_request:
jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: checkout pushed commit
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - uses: docker/setup-buildx-action@v2
    - uses: docker/build-push-action@v4
      with:
        context: .
        cache-from: type=gha
        cache-to: type=gha,mode=max
    - name: change owner
      run: sudo chown -R 1000:1000 ./ 
    - name: run test on docker-compose
      env:
        MYWEBSITE_URL: "${{ secrets.MYWEBSITE_URL }}"
        MYWEBSITE_NAME: "${{ secrets.MYWEBSITE_NAME }}"
        API_KEY: "${{ secrets.FIREBASE_API_KEY }}"
        AUTH_DOMAIN: "${{ secrets.FIREBASE_AUTH_DOMAIN }}"
        PROJECT_ID: "${{ secrets.FIREBASE_PROJECT_ID }}"
        STORAGE_BUCKET: "${{ secrets.FIREBASE_STORAGE_BUCKET }}"
        MESSAGING_SENDER_ID: "${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}"
        APP_ID: "${{ secrets.FIREBASE_APP_ID }}"
      run: |
        docker compose build
        docker compose run --rm react yarn install
        docker compose run --rm react yarn lint
        docker compose up -d emulator
        docker compose run --rm react yarn test
      working-directory: ./
