name: FrontEnd Testing
on:
  pull_request:
jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: checkout pushed commit
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
    - name: change owner
      run: sudo chown -R 1000:1000 ./ 
    - name: run test on docker-compose
      env:
        FIREBASE_AUTH_EMULATOR_HOST: "emulator:9099"
      run: |
        docker compose build
        docker compose run --rm react yarn install
        docker compose run --rm react yarn lint
        docker compose up -d emulator
        docker compose run --rm react yarn test
      working-directory: ./
