name: Deploy to Firebase Hosting on merge
'on':
 push:
   branches:
     - main
env:
  NODE_VER: 18.16.0-slim
  FIREBASE_VER: 12.3.0
  VOLUME_EXTERNAL: true
jobs:
  build_and_deploy:
    name: Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: checkout pushed commit
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: docker/setup-buildx-action@v2
      - uses: docker/build-push-action@v4
        with:
          context: ./frontend
          build-args: |
            NODE_VER=${{ env.NODE_VER }}
            FIREBASE_VER=${{ env.FIREBASE_VER }}
          tags: behavior-analysis-react:latest
          load: true
          cache-from: type=gha,scope=react
          cache-to: type=gha,mode=max,scope=react
      - name: change owner
        run: sudo chown -R 1000:1000 ./
      - name: docker volume create
        run: |
          docker volume create behavior-analysis_node_modules
          sudo chown -R 1000:1000 /var/lib/docker/volumes/behavior-analysis_node_modules
      - name: Build
        env:
          MYWEBSITE_URL: "${{ secrets.MYWEBSITE_URL }}"
          MYWEBSITE_NAME: "${{ secrets.MYWEBSITE_NAME }}"
          API_KEY: "${{ secrets.FIREBASE_API_KEY }}"
          AUTH_DOMAIN: "${{ secrets.FIREBASE_AUTH_DOMAIN }}"
          PROJECT_ID: "${{ secrets.FIREBASE_PROJECT_ID }}"
          STORAGE_BUCKET: "${{ secrets.FIREBASE_STORAGE_BUCKET }}"
          MESSAGING_SENDER_ID: "${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}"
          APP_ID: "${{ secrets.FIREBASE_APP_ID }}"
        run: |
          docker compose run --rm react yarn install
          docker compose run --rm react yarn build
      - name: Deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_TOKEN }}'
          channelId: live
          projectId: '${{ secrets.FIREBASE_PROJECTID }}'
          entryPoint: ./frontend
